### ISSUE TITLE
Revisions needed on training book

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/PredictiveEcology.org#12]
@CeresBarros to check the following new sections

- [x] Installing R
- [x] R packages for book
- [x] Troubleshooting R package installation

**Comment by CeresBarros** [comment]
@eliotmcintire I moved pkg intallation (when not part of example code) to a pre-rendered script (`R/installpkgs.R`), this alleviates the setup chunks a little and allows us to use a proj lib path w/o having to pass it to each .qmd

perhaps sub ideal as we still need to remember to add pkgs to this script. Also, I'm having issues installing `ggplot2`/`terra`:
```
Warning message:
In Require::Require(c("ggplot2", "reproducible", "SpaDES.core",  :
  ggplot2, terra (>= 1.7-46) could not be installed; package doesn't exist or the version specification cannot be met

```

**Comment by CeresBarros** [comment]
@eliotmcintire when you can see new version of Troubleshooting R package installation chapter, as I've changed it quite considerably

**Comment by eliotmcintire** [comment]
Looks good. The inline R code causes an error `{r userLib <- Sys.getenv("R_LIBS_USER")}` doesn't work for me. If I just remove the end braces and the lower case r `{r ... }` it works fine. Can we do this?
